export const recommended = [
  {
    id: 'nnxCEQGuVpQcaYVO7dfl',
    image: 'vIWycwQIw44tvc0Qmekj.jpg',
    imgHover: '2aCyJIiwYHof70reuWov.jpg',
    title: 'Cooler for DEEPCOOL MF120 GT case',
    price: 34.7,
    brand: '54',
    category: 'housing-accessories',
  },

  {
    id: 'mRAhdzI38CR2ole1WSxd',
    image: 'BV3SldMf1vgJHgZagi8i.jpg',
    imgHover: 'YEiCw3zpnszeotr3P1R3.jpg',
    title: 'Flash drive KINGSTON 8GB DataTraveler 2000 (Interface 3.1)',
    price: 71.4,
    brand: '66',
    category: 'flash-drives',
  },
  {
    id: 'liw5hHrycvJsfw6foPsg',
    image: 'G4M0HPQrkEDF9lBJpP1l.jpg',
    imgHover: 'QzEwysmS91arS1z2SiZn.jpg',
    title:
      'MICROSOFT SURFACE PRO 8 Ultrabook (Intel® Core i5-1135G7 Processor)',
    price: 1275.5,
    brand: '116',
    category: 'laptops',
  },

  {
    id: 'z1VI7uP0eyDx5cgpQ695',
    image: '9DDdBRwaz5m0ZoCl88Qc.jpg',
    imgHover: '9DDdBRwaz5m0ZoCl88Qc.jpg',
    title: '(used) RAM for laptop SHARETRONIC 2GB (DDR3 - 1600 MHz)',
    price: 2.6,
    brand: '210',
    category: 'ram-for-laptops',
  },

  {
    id: 'ahgPEVGYEqjKiumIrLxZ',
    image: 'JlYwu3kYyhUp0bLX3ytN.jpg',
    imgHover: '826svcmeAvkS21njTLYQ.jpg',
    title: 'Smart watch 2E MOTION GT (Black with silver color)',
    price: 34.7,
    brand: '148',
    category: 'smart-watch',
  },

  {
    id: 'yhD9LnVB3Yt9OzfYxpX6',
    image: '37xHZ7bwDRZVR3OwqcG2.jpg',
    imgHover: '7OzVsWY6epIF4soJfFvw.jpg',
    title:
      'UGREEN CD177 Wireless Charger for Apple Watch (Magnetic Module with Cable / USB)',
    price: 22.4,
    brand: '119',
    category: 'gadget-chargers',
  },
  {
    id: 's06GlGEhxQZSDrYSsTIg',
    image: 'hCfJP01ILRX1JXLLJwqn.jpg',
    imgHover: '1qJugXLJMmzitHMkUF5U.jpg',
    title:
      'LENOVO IdeaCentre 3 24ITL6 All-in-One (Intel® Core i5-1135G7 Processor)',
    price: 938.8,
    brand: '14',
    category: 'monoblocks',
  },
  {
    id: 'puXsI6HLCNymC6CEdISA',
    image: 'MDKCOBqLwPMivoS83ctP.jpg',
    imgHover: '4pZseiIXh0ONiGZMNcGF.jpg',
    title: 'Wireless phone charger UGREEN CD256 for the car',
    price: 18.9,
    brand: '119',
    category: 'gadget-chargers',
  },
  {
    id: 'iNhG5T93PN2XCixE7lzm',
    image: 'lHOl3p55fEsMalI0J2pp.jpg',
    imgHover: 'l99EbRYPyR62CvX1rCV1.jpg',
    title: 'Gaming monitor 2E 34" G3420B',
    price: 438.8,
    brand: '148',
    category: 'monitors',
  },
  {
    id: 'EJLMnoh12mEHLtFu9PGZ',
    image: 'RRcx0ot0CK3hyBmYdgBe.jpg',
    imgHover: 'G3FRsFb3eX61RBEfHEL2.jpg',
    title: 'HP 27" M27fe Monitor',
    price: 193.9,
    brand: '13',
    category: 'monitors',
  },
  {
    id: 'VckZKlbta4m8dfUm5enH',
    image: 'gRuRiwGiGBV0Hr4sImQT.jpg',
    imgHover: 'asclUy7z5nOPisRiNeTa.jpg',
    title: 'Computer case for ASUS TUF GAMING GT301',
    price: 107.1,
    brand: '105',
    category: 'pc-cases',
  },
  {
    id: 'IrGxe6TneRAUP3NHQQaK',
    image: 'SUBKD4ES9JOzwHt4kGIR.jpg',
    imgHover: 'lDpOVtSD4ByPjsS8sNNO.jpg',
    title: 'Computer case SIGNATURE E190',
    price: 23.5,
    brand: '113',
    category: 'pc-cases',
  },
  {
    id: 'p25BtQpFQUlUOrdGGpHk',
    image: 'zdShXoqjjlru89BkxeNO.jpg',
    imgHover: 'rIYla1ZF9DQOIzfdwChW.jpg',
    title: 'GIGABYTE GTX 1660 OC EDITION graphics card',
    price: 306.1,
    brand: '55',
    category: 'video-cards',
  },
  {
    id: 'HvGwLz9cnhxwb0CWBnSH',
    image: 'tPvGXvOoN7G843sMXO5h.jpg',
    imgHover: 'qmkG8lRWIjylx4DSvjrD.jpg',
    title: 'Solid State Drive (SSD) KINGSTON 120 GB (SATA 2.5 inch Interface)',
    price: 18.4,
    brand: '66',
    category: 'solid-state-drives',
  },
  {
    id: 'Z5A4yNuqZABA96ciC5am',
    image: 'wpa82lsa0Mm87KJ15uEo.jpg',
    imgHover: 'sYujs271svPze6TH7LCT.jpg',
    title: 'Liquid cooling DEEPCOOL INFINITY LS720 WH (White)',
    price: 158.2,
    brand: '54',
    category: 'air-and-liquid-cooling',
  },
  {
    id: 'jYb0V8tsqdiOQFWOCehG',
    image: 'FaE9Lp4ouXFOsTY1kKsV.jpg',
    imgHover: 'hfL3SxhLwXhwptRW38Dl.jpg',
    title: 'Computer mouse DREAM MACHINES DM5 BLINK',
    price: 43.9,
    brand: '150',
    category: 'computer-mice',
  },
  {
    id: 'BdmdK5KOiduZYHhxyGsh',
    image: 'uT4jdeEE8QFJ4CNGIQmJ.jpg',
    imgHover: 'xe1ob1dp2CGamqRtO3zL.jpg',
    title: 'Mouse pad 2E SPEED XL',
    price: 8.2,
    brand: '148',
    category: 'mouse-pads',
  },
];

export const popular = [
  {
    id: 'BwkHlz2Zl6kaAorcj7VU',
    image: 'T86fyYRYhotUgH8OE1JR.jpg',
    imgHover: 'EZc3N9nxWvbCOEW8VwL5.jpg',
    title: 'Computer mouse KINGSTON HYPERX PULSEFIRE DART',
    price: 51,
    brand: '66',
    category: 'computer-mice',
  },
  {
    id: 'p7Rl9Aq35mecc5HvVl90',
    image: '8fuhWyEvMUlDlAcuyD1H.jpg',
    imgHover: 'xKgkIwQ51zipag8tNBgo.jpg',
    title: 'Keyboard UGREEN KU002 (Wired USB / Black color)',
    price: 6.6,
    brand: '119',
    category: 'keyboards',
  },
  {
    id: 'MZ1THOSEv17NXAXKmeIw',
    image: '38LTmZDq6zsfgyRucIlv.jpg',
    imgHover: 'MUljAgVtqWyWK9bnkIz6.jpg',
    title: 'ASUS ROG STRIX FUSION 500 headphones',
    price: 163.3,
    brand: '105',
    category: 'headphones-and-headsets',
  },
  {
    id: 'c7twuhkG2C9v0HZL8HSF',
    image: 'yp5iIDBHajpOUg1s98HS.jpg',
    imgHover: 'y5gB2vEcTZW5UMbZULum.jpg',
    title: 'UGREEN CM219 USB Multiplier (4 Ports / USB 3.0 / Length 15 cm)',
    price: 7.4,
    brand: '119',
    category: 'dockers-and-replicators',
  },

  {
    id: 'h8K8zClPcytcBx6BOlpU',
    image: '1EOA2323Sx5D24YgheoC.jpg',
    imgHover: 'GwuyGL6yzYarF3kU0IQq.jpg',
    title: 'Mouse pad ASUS ROG SHEATH ELECTRO PUNK',
    price: 30.6,
    brand: '105',
    category: 'mouse-pads',
  },
  {
    id: 'V7W18d5NtoNuDILNdwkM',
    image: '3vghfpBCEdnFSac2RQZC.jpg',
    imgHover: '3vghfpBCEdnFSac2RQZC.jpg',
    title: 'Mouse pad UGREEN CY016 SMALL',
    price: 0.7,
    brand: '119',
    category: 'mouse-pads',
  },
  {
    id: 'uOXbJvwDJLzrPJHsHEgI',
    image: 'pLfU5yAfoY5iLrMca4N5.jpg',
    imgHover: 'nW4VIEq3xhTJFRgMZo0Y.jpg',
    title: 'UGREEN WS118 HiTune X6 Headphones',
    price: 39.8,
    brand: '119',
    category: 'headphones-and-headsets',
  },
  {
    id: 'sjTnNdDuRDhCYEMZGLoP',
    image: 'dQsQfuOSjFXvknBqlxqo.jpg',
    imgHover: '74eAelshCPTaAQswBfjM.jpg',
    title: 'Speaker 2E SoundXPod (Black)',
    price: 21.4,
    brand: '148',
    category: 'portable-speakers',
  },
  {
    id: 'Pe3aOuBZrRb3GcJAjSl2',
    image: 'hGnQzuUzbBOss66sK6Tf.jpg',
    imgHover: '5fRWpkkG1YzoSW9HlEQ8.jpg',
    title: 'NINTENDO SWITCH OLED Portable Game Console',
    price: 418.4,
    brand: '183',
    category: 'game-consoles',
  },
  {
    id: 'c7twuhkG2C9v0HZL8HSF',
    image: 'yp5iIDBHajpOUg1s98HS.jpg',
    imgHover: 'y5gB2vEcTZW5UMbZULum.jpg',
    title: 'UGREEN CM219 USB Multiplier (4 Ports / USB 3.0 / Length 15 cm)',
    price: 7.4,
    brand: '119',
    category: 'dockers-and-replicators',
  },
  {
    id: 'XVXvPqcizi3S2P0IRlhr',
    image: 'YvuEXScOsnedvr2M5txS.jpg',
    imgHover: 'xkolBqnk1kjWonCSbTd3.jpg',
    title: 'UGREEN TYPE-C USB Multiplier (4 Ports / White Color)',
    price: 9.4,
    brand: '119',
    category: 'dockers-and-replicators',
  },
  {
    id: 'fooNkpeVs3MiuGmH6V72',
    image: 'KIMgTMBz4vOXQvK6RO9a.jpg',
    imgHover: 'VqL730wfDlSJqOsoVcqO.jpg',
    title: 'SEAGATE 2TB EXPANSION External Hard Drive (Black)',
    price: 59.2,
    brand: '57',
    category: 'external-hard-drives',
  },
  {
    id: 'hGwUR18vmWjQ5y1MDQHq',
    image: 'y5FsUyYpJZGr1nx9PiSM.jpg',
    imgHover: 'h96dZDrFrm19ueREqaLI.jpg',
    title: 'TOSHIBA 1TB Canvio Advance External Hard Drive (White)',
    price: 46.9,
    brand: '82',
    category: 'external-hard-drives',
  },
  {
    id: 'mbyhtWuyaEQxthXEx1LE',
    image: 'zqqTVAmgOFuAvqxeQjD6.jpg',
    imgHover: 'CWmmIIWRjD4zZoGrqxKY.jpg',
    title:
      'Docking station UGREEN CM198 for hard drives (Interface SATA 2.5" and 3.5" / USB 3.0 / 2 Slots)',
    price: 24.5,
    brand: '119',
    category: 'cases-and-stations-for-hard-drives',
  },
  {
    id: 'vGz91ikKt0tm9Q1VX2bo',
    image: '7TpK01PhbiEzc21x7tSV.jpg',
    imgHover: 'gNke3CNu1ptj2K3nqZaG.jpg',
    title: 'Flash drive SANDISK 64GB EXTREME (Interface 3.0)',
    price: 16.8,
    brand: '28',
    category: 'flash-drives',
  },
  {
    id: 'X3Ivcy897bq7jX7tDKJX',
    image: 'SfwdOSVLApMlOa2bTqRj.jpg',
    imgHover: 'tyv4okogxHgSb6iWUaej.jpg',
    title: 'ACER ASPIRE 3 A315 Laptop (Intel® Core i7-1165G7 Processor)',
    price: 714.3,
    brand: '18',
    category: 'laptops',
  },
  {
    id: 'X9316Dtnl4JDmB1MErTy',
    image: '6Iwu5fUwQnVpRnDXaAGe.jpg',
    imgHover: 'iK6lN0TY5mGBDM0rlapK.jpg',
    title: 'Backpack RIVACASE 7562 (Diagonal 15.6" / Gray color)',
    price: 18.4,
    brand: '36',
    category: 'bags-and-backpacks',
  },
  {
    id: 'jTLEuibE31sg420KEtjX',
    image: 'EQPmr5fILjCo8rzjoajm.jpg',
    imgHover: '9mivQvIKWzI6M3QaCx17.jpg',
    title: 'RIVACASE 8455 bag (Diagonal 17.3" / Black color)',
    price: 29.6,
    brand: '36',
    category: 'bags-and-backpacks',
  },
  {
    id: 'uPpi0FgWBW8VRRT3Vqss',
    image: 'ooVBbwNOjxab3F6jZlSa.jpg',
    imgHover: 'ooVBbwNOjxab3F6jZlSa.jpg',
    title: 'Laptop battery for DELL E7420-E7440-PFXCR (Duplicate)',
    price: 33.7,
    brand: '20',
    category: 'laptop-batteries',
  },
  {
    id: 'z1VI7uP0eyDx5cgpQ695',
    image: '9DDdBRwaz5m0ZoCl88Qc.jpg',
    imgHover: '9DDdBRwaz5m0ZoCl88Qc.jpg',
    title: '(used) RAM for laptop SHARETRONIC 2GB (DDR3 - 1600 MHz)',
    price: 2.6,
    brand: '210',
    category: 'ram-for-laptops',
  },
  {
    id: 'eIZPOwYi88lSrlVJHl84',
    image: 'vUSoO7fcMMQKeJBvHMVA.jpg',
    imgHover: 'VNjCuqpIUSZ01NLxMhNN.jpg',
    title: 'Smart watch 2E ALPHA X (Black with silver color)',
    price: 35.7,
    brand: '148',
    category: 'smart-watch',
  },
];

export const homePage = [
  {
    category: 'recommended',
    name: 'Recommended products',
    link: '/recommended',
    products: recommended.slice(0, 8),
  },
  {
    category: 'Popular',
    name: 'Popular products',
    link: '/popular',
    products: popular.slice(0, 8),
  },
  {
    category: 'Monitor',
    name: 'Monitor',
    link: '/categories/monitors',
    products: [
      {
        id: 'iNhG5T93PN2XCixE7lzm',
        image: 'lHOl3p55fEsMalI0J2pp.jpg',
        imgHover: 'l99EbRYPyR62CvX1rCV1.jpg',
        title: 'Gaming monitor 2E 34" G3420B',
        price: 438.8,
        brand: '148',
        category: 'monitory',
      },
      {
        id: 'a7FqFavFLKMik1JW0j2O',
        image: 'UgVsjp9z6NAAUfw68V1X.jpg',
        imgHover: 'PjXDYp0V2KBFglujvcfW.jpg',
        title: 'ASUS ROG STRIX 27" XG27AQ gaming monitor',
        price: 510.2,
        brand: '105',
        category: 'monitory',
      },
      {
        id: 'xqpsBk7VIINqtfuSwyI2',
        image: 'bxXQQXpjNOSbujx30jWE.jpg',
        imgHover: '8XanchiBE3ZMeBobYIOB.jpg',
        title: 'SAMSUNG 27" Odyssey G3 Gaming Monitor',
        price: 250,
        brand: '11',
        category: 'monitory',
      },
      {
        id: 'pQvSEpnKsoEBnw3t4a4o',
        image: 'zdWN6v0DhAlAiYbwaZxf.jpg',
        imgHover: '3WgTcmmySze3XwBv6DBH.jpg',
        title: 'SAMSUNG 34" Odyssey G8 OLED Gaming Monitor',
        price: 1765.3,
        brand: '11',
        category: 'monitory',
      },
    ],
  },
  {
    category: 'Laptops',
    name: 'Laptops',
    link: '/categories/laptops',
    products: [
      {
        id: 'O7tulMsPknsWAspelwyS',
        image: 'ackKGWyLq6DY3yPNqQPK.jpg',
        imgHover: 'S2Ml3LDNjsGuXGs3uhTZ.jpg',
        title:
          'ASUS ROG STRIX G513RC Gaming Laptop (AMD Ryzen7 6800H Processor)',
        price: 1377.6,
        brand: '105',
        category: 'notebooks',
      },
      {
        id: 'cmXSAAQLW8hDLyft0GYO',
        image: '1un3Je0DEcLt1lKuzak0.jpg',
        imgHover: 'M3aQO7HwT7uRSA8oaTj4.jpg',
        title: 'ASUS TUF FA707R Gaming Laptop (AMD Ryzen7 6800H Processor)',
        price: 1387.8,
        brand: '105',
        category: 'notebooks',
      },
      {
        id: 'wZfSOLQKfCIW8L2wlVd0',
        image: 'UClDHs3I2vF2fQZVeQAT.jpg',
        imgHover: 'dFkQ7faUX1hovDfOYSJN.jpg',
        title: 'ACER ASPIRE 3 A315 Laptop (Intel® Core i5-1135G7 Processor)',
        price: 530.6,
        brand: '18',
        category: 'notebooks',
      },
      {
        id: 'm1N7E70iKqf7wK35W6UN',
        image: 'ljBVDRjRX47zdYt39igA.jpg',
        imgHover: 'hOM3vs09uPMV56wuQgPM.jpg',
        title: 'ACER ASPIRE 7 A715 Laptop (Intel® Core i5-12450H Processor)',
        price: 744.9,
        brand: '18',
        category: 'notebooks',
      },
    ],
  },
  {
    category: 'storage',
    name: 'Storage',
    link: '/categories/internal-hard-disks',
    products: [
      {
        id: 'AwgbdMSoXwz9mHzXqOkk',
        image: 'TuuKBFcPwq50FtsQmMR8.jpg',
        imgHover: 'TuuKBFcPwq50FtsQmMR8.jpg',
        title: 'SEAGATE 16TB Exos X18 Internal Hard Drive',
        price: 336.7,
        brand: '57',
        category: 'vnutrennie zyostkie disk hdd',
      },
      {
        id: 'xQL1orpGYKYdjJ2tYhNm',
        image: 'j9B0QyzbSOv0YlAKpAJu.jpg',
        imgHover: 'j9B0QyzbSOv0YlAKpAJu.jpg',
        title: 'SEAGATE 18TB Exos X18 Internal Hard Drive',
        price: 367.3,
        brand: '57',
        category: 'vnutrennie zyostkie disk hdd',
      },
      {
        id: 'MPVKugSHN15WkiBsGn92',
        image: 's9Txoa4dVVERufhsJMpb.jpg',
        imgHover: 's9Txoa4dVVERufhsJMpb.jpg',
        title: 'SEAGATE 1TB SkyHawk Surveillance Internal Hard Drive',
        price: 45.9,
        brand: '57',
        category: 'vnutrennie zyostkie disk hdd',
      },
      {
        id: 'WHTQ6Hzn00a17zAxivyu',
        image: 'jh2c7vgdqQUqh2gJ8N1G.jpg',
        imgHover: 'jh2c7vgdqQUqh2gJ8N1G.jpg',
        title: 'SEAGATE 2TB IronWolf Internal Hard Drive',
        price: 83.7,
        brand: '57',
        category: 'vnutrennie zyostkie disk hdd',
      },
    ],
  },
];

export const brands = [
  {
    image: '/img/brand-icons/1gMiQgFD04.png',
    id: '63c9823de741bf8437d2779e',
  },
  {
    image: '/img/brand-icons/6UJudvMU9M.png',
    id: '63c9823d4e0a18e9c9934bd1',
  },
  {
    image: '/img/brand-icons/7bU9wq4j6S.png',
    id: '63c9823da848e6b6f276c00e',
  },
  {
    image: '/img/brand-icons/8mv9AgXux5.png',
    id: '63c9823d2226be88ea5ca115',
  },
  {
    image: '/img/brand-icons/b8JX2gBze2.png',
    id: '63c9823d4bcc91ce54703339',
  },
  {
    image: '/img/brand-icons/dVPHFcrQxi.png',
    id: '63c9823d03163bb0d6d3e2c3',
  },
  {
    image: '/img/brand-icons/E3tdOUvkRJ.png',
    id: '63c9823d9b1e23bebff25b7b',
  },
  {
    image: '/img/brand-icons/FhnXngTVWY.png',
    id: '63c9823d0633f39697ade56f',
  },
  {
    image: '/img/brand-icons/GKJk1Y4PxV.png',
    id: '63c9823d54703ce8fa1085e3',
  },
  {
    image: '/img/brand-icons/k3bYlobwmQ.png',
    id: '63c9823d4e0f029e3cfe441b',
  },
  {
    image: '/img/brand-icons/Kkb4LSYqnw.png',
    id: '63c9823dd62129d60ceac10f',
  },
  {
    image: '/img/brand-icons/nSdCOFkrIy.png',
    id: '63c9823dd7d67a5da2e758b7',
  },
  {
    image: '/img/brand-icons/zRA5qvz2P9.png',
    id: '63c9823d22b2a7509a988fd4',
  },
  {
    image: '/img/brand-icons/YhfdCoTOIb.png',
    id: '63c9823d69a593234a9585e7',
  },
  {
    image: '/img/brand-icons/WnyQd0Hfo2.png',
    id: '63c9823dd2fc150348fb4d33',
  },
  {
    image: '/img/brand-icons/VDqRlrqzDy.png',
    id: '63c9823d28d9cb786c32e597',
  },
  {
    image: '/img/brand-icons/TJGR84g5Wj.png',
    id: '63c9823ddd57ee934746bd54',
  },
  {
    image: '/img/brand-icons/QV8oixWNnt.png',
    id: '63c9823dc366f8d7028a97b9',
  },
];

export const sliders = {
  brands: [
    {
      image: '/img/mini slides/MSlide3.jpg',
      link: '/products/p7Rl9Aq35mecc5HvVl90',
    },
    {
      image: '/img/mini slides/MSlide4.gif',
      link: '/products/LdUVJLsikx9ZsgItlB7f',
    },
    {
      image: '/img/mini slides/MSlide5.jpg',
      link: '/products/dz2jlS0fqeisPAfQ6IeJ',
    },
    {
      image: '/img/mini slides/MSlide6.gif',
      link: '/products/TqUrnUUWIx3UOqc75nyB',
    },
    {
      image: '/img/mini slides/MSlide7.jpg',
      link: '/products/LcpWjMbYmCBk5W9Mypqy',
    },
    {
      image: '/img/mini slides/MSlide8.jpg',
      link: '/products/aIftAj9BLrwKotsDYFJs',
    },
  ],
  mainSliders: [
    {
      image: '/img/main images/slider1.jpg',
      link: '/categories/home-attributes',
    },
    {
      image: '/img/main images/slider2.jpg',
      link: '/categories/video-cards',
    },
    {
      image: '/img/main images/slider3.jpg',
      link: '/categories/massagers',
    },

    {
      image: '/img/main images/slider5.jpg',
      link: '/products/cGMjDwFsJkQkZhcsNKwm',
    },
    {
      image: '/img/main images/slider6.jpg',
      link: '/search?term=ASUS',
    },
    {
      image: '/img/main images/slider7.jpg',
      link: '/categories/home-attributes',
    },
    {
      image: '/img/main images/slider8.jpg',
      link: '/search?term=SONY',
    },
  ],
};
